### ISSUE TITLE
T6 - Adequar dimensões do campo virtual de pebolim

### ISSUE THREAD

**Issue by guilherme1guy** [pi2-2020-1-pebolim/pebolim-sim#5]
**Objetivo**:  ficar com uma escala real de uma mesa

**Comentário**: 

**Dependência**: #3

**Comment by DanMke** [comment]
http://www.pebolimbrasil.com.br/p32020/ficha-tecnica

**Comment by guilherme1guy** [comment]
https://github.com/pi2-2020-1-pebolim/pebolim-sim/pull/15
